name: Deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Yarn install
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Yarn build
        run: |
          yarn build

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.OMNI_GH_KEY }}
          SOURCE: 'dist/'
          REMOTE_HOST: ${{ secrets.OMNI_HOST }}
          REMOTE_USER: ${{ secrets.OMNI_USER }}
          TARGET: '~/caddy/site/rest.quest/'
          EXCLUDE: '/dist/, /node_modules/'
